// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vinyl.proto

package vinyl

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Artist ...
type Artist struct {
	Namevariations       []string  `protobuf:"bytes,1,rep,name=namevariations,proto3" json:"namevariations,omitempty"`
	Profile              string    `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	ReleasesUrl          string    `protobuf:"bytes,3,opt,name=releases_url,json=releasesUrl,proto3" json:"releases_url,omitempty"`
	ResourceUrl          string    `protobuf:"bytes,4,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Uri                  string    `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	Urls                 []string  `protobuf:"bytes,6,rep,name=urls,proto3" json:"urls,omitempty"`
	DataQuality          string    `protobuf:"bytes,7,opt,name=data_quality,json=dataQuality,proto3" json:"data_quality,omitempty"`
	Id                   int64     `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	Images               []*Image  `protobuf:"bytes,9,rep,name=images,proto3" json:"images,omitempty"`
	Members              []*Member `protobuf:"bytes,10,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Artist) Reset()         { *m = Artist{} }
func (m *Artist) String() string { return proto.CompactTextString(m) }
func (*Artist) ProtoMessage()    {}
func (*Artist) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{0}
}

func (m *Artist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Artist.Unmarshal(m, b)
}
func (m *Artist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Artist.Marshal(b, m, deterministic)
}
func (m *Artist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Artist.Merge(m, src)
}
func (m *Artist) XXX_Size() int {
	return xxx_messageInfo_Artist.Size(m)
}
func (m *Artist) XXX_DiscardUnknown() {
	xxx_messageInfo_Artist.DiscardUnknown(m)
}

var xxx_messageInfo_Artist proto.InternalMessageInfo

func (m *Artist) GetNamevariations() []string {
	if m != nil {
		return m.Namevariations
	}
	return nil
}

func (m *Artist) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *Artist) GetReleasesUrl() string {
	if m != nil {
		return m.ReleasesUrl
	}
	return ""
}

func (m *Artist) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *Artist) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Artist) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *Artist) GetDataQuality() string {
	if m != nil {
		return m.DataQuality
	}
	return ""
}

func (m *Artist) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Artist) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Artist) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

// ArtistSource ...
type ArtistSource struct {
	Anv                  string   `protobuf:"bytes,1,opt,name=anv,proto3" json:"anv,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Join                 string   `protobuf:"bytes,3,opt,name=join,proto3" json:"join,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ResourceUrl          string   `protobuf:"bytes,5,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Tracks               string   `protobuf:"bytes,7,opt,name=tracks,proto3" json:"tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArtistSource) Reset()         { *m = ArtistSource{} }
func (m *ArtistSource) String() string { return proto.CompactTextString(m) }
func (*ArtistSource) ProtoMessage()    {}
func (*ArtistSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{1}
}

func (m *ArtistSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtistSource.Unmarshal(m, b)
}
func (m *ArtistSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtistSource.Marshal(b, m, deterministic)
}
func (m *ArtistSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtistSource.Merge(m, src)
}
func (m *ArtistSource) XXX_Size() int {
	return xxx_messageInfo_ArtistSource.Size(m)
}
func (m *ArtistSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtistSource.DiscardUnknown(m)
}

var xxx_messageInfo_ArtistSource proto.InternalMessageInfo

func (m *ArtistSource) GetAnv() string {
	if m != nil {
		return m.Anv
	}
	return ""
}

func (m *ArtistSource) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArtistSource) GetJoin() string {
	if m != nil {
		return m.Join
	}
	return ""
}

func (m *ArtistSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ArtistSource) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *ArtistSource) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ArtistSource) GetTracks() string {
	if m != nil {
		return m.Tracks
	}
	return ""
}

// Community ...
type Community struct {
	Contributors         []*Contributor `protobuf:"bytes,1,rep,name=contributors,proto3" json:"contributors,omitempty"`
	DataQuality          string         `protobuf:"bytes,2,opt,name=data_quality,json=dataQuality,proto3" json:"data_quality,omitempty"`
	Have                 int64          `protobuf:"varint,3,opt,name=have,proto3" json:"have,omitempty"`
	Rating               *Rating        `protobuf:"bytes,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Status               string         `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Submitter            *Submitter     `protobuf:"bytes,6,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Want                 int64          `protobuf:"varint,7,opt,name=want,proto3" json:"want,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Community) Reset()         { *m = Community{} }
func (m *Community) String() string { return proto.CompactTextString(m) }
func (*Community) ProtoMessage()    {}
func (*Community) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{2}
}

func (m *Community) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Community.Unmarshal(m, b)
}
func (m *Community) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Community.Marshal(b, m, deterministic)
}
func (m *Community) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Community.Merge(m, src)
}
func (m *Community) XXX_Size() int {
	return xxx_messageInfo_Community.Size(m)
}
func (m *Community) XXX_DiscardUnknown() {
	xxx_messageInfo_Community.DiscardUnknown(m)
}

var xxx_messageInfo_Community proto.InternalMessageInfo

func (m *Community) GetContributors() []*Contributor {
	if m != nil {
		return m.Contributors
	}
	return nil
}

func (m *Community) GetDataQuality() string {
	if m != nil {
		return m.DataQuality
	}
	return ""
}

func (m *Community) GetHave() int64 {
	if m != nil {
		return m.Have
	}
	return 0
}

func (m *Community) GetRating() *Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

func (m *Community) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Community) GetSubmitter() *Submitter {
	if m != nil {
		return m.Submitter
	}
	return nil
}

func (m *Community) GetWant() int64 {
	if m != nil {
		return m.Want
	}
	return 0
}

// Company ...
type Company struct {
	Catno                string   `protobuf:"bytes,1,opt,name=catno,proto3" json:"catno,omitempty"`
	EntityType           string   `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityTypeName       string   `protobuf:"bytes,3,opt,name=entity_type_name,json=entityTypeName,proto3" json:"entity_type_name,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	ResourceUrl          string   `protobuf:"bytes,6,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}
func (*Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{3}
}

func (m *Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Company.Unmarshal(m, b)
}
func (m *Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Company.Marshal(b, m, deterministic)
}
func (m *Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Company.Merge(m, src)
}
func (m *Company) XXX_Size() int {
	return xxx_messageInfo_Company.Size(m)
}
func (m *Company) XXX_DiscardUnknown() {
	xxx_messageInfo_Company.DiscardUnknown(m)
}

var xxx_messageInfo_Company proto.InternalMessageInfo

func (m *Company) GetCatno() string {
	if m != nil {
		return m.Catno
	}
	return ""
}

func (m *Company) GetEntityType() string {
	if m != nil {
		return m.EntityType
	}
	return ""
}

func (m *Company) GetEntityTypeName() string {
	if m != nil {
		return m.EntityTypeName
	}
	return ""
}

func (m *Company) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Company) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Company) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

// Contributor ...
type Contributor struct {
	ResourceUrl          string   `protobuf:"bytes,1,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contributor) Reset()         { *m = Contributor{} }
func (m *Contributor) String() string { return proto.CompactTextString(m) }
func (*Contributor) ProtoMessage()    {}
func (*Contributor) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{4}
}

func (m *Contributor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contributor.Unmarshal(m, b)
}
func (m *Contributor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contributor.Marshal(b, m, deterministic)
}
func (m *Contributor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contributor.Merge(m, src)
}
func (m *Contributor) XXX_Size() int {
	return xxx_messageInfo_Contributor.Size(m)
}
func (m *Contributor) XXX_DiscardUnknown() {
	xxx_messageInfo_Contributor.DiscardUnknown(m)
}

var xxx_messageInfo_Contributor proto.InternalMessageInfo

func (m *Contributor) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *Contributor) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// DatabaseService ...
type DatabaseService struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabaseService) Reset()         { *m = DatabaseService{} }
func (m *DatabaseService) String() string { return proto.CompactTextString(m) }
func (*DatabaseService) ProtoMessage()    {}
func (*DatabaseService) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{5}
}

func (m *DatabaseService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabaseService.Unmarshal(m, b)
}
func (m *DatabaseService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabaseService.Marshal(b, m, deterministic)
}
func (m *DatabaseService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabaseService.Merge(m, src)
}
func (m *DatabaseService) XXX_Size() int {
	return xxx_messageInfo_DatabaseService.Size(m)
}
func (m *DatabaseService) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabaseService.DiscardUnknown(m)
}

var xxx_messageInfo_DatabaseService proto.InternalMessageInfo

// Format ...
type Format struct {
	Descriptions         []string `protobuf:"bytes,1,rep,name=descriptions,proto3" json:"descriptions,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Qty                  string   `protobuf:"bytes,3,opt,name=qty,proto3" json:"qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Format) Reset()         { *m = Format{} }
func (m *Format) String() string { return proto.CompactTextString(m) }
func (*Format) ProtoMessage()    {}
func (*Format) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{6}
}

func (m *Format) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Format.Unmarshal(m, b)
}
func (m *Format) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Format.Marshal(b, m, deterministic)
}
func (m *Format) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Format.Merge(m, src)
}
func (m *Format) XXX_Size() int {
	return xxx_messageInfo_Format.Size(m)
}
func (m *Format) XXX_DiscardUnknown() {
	xxx_messageInfo_Format.DiscardUnknown(m)
}

var xxx_messageInfo_Format proto.InternalMessageInfo

func (m *Format) GetDescriptions() []string {
	if m != nil {
		return m.Descriptions
	}
	return nil
}

func (m *Format) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Format) GetQty() string {
	if m != nil {
		return m.Qty
	}
	return ""
}

// Identifier ...
type Identifier struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{7}
}

func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (m *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(m, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Identifier) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Image ...
type Image struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width                int64    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	ResourceUrl          string   `protobuf:"bytes,3,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Uri                  string   `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	Uri150               string   `protobuf:"bytes,6,opt,name=uri150,proto3" json:"uri150,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{8}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Image) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *Image) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Image) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Image) GetUri150() string {
	if m != nil {
		return m.Uri150
	}
	return ""
}

// LabelSource ...
type LabelSource struct {
	Catno                string   `protobuf:"bytes,1,opt,name=catno,proto3" json:"catno,omitempty"`
	EntityType           string   `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ResourceUrl          string   `protobuf:"bytes,5,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabelSource) Reset()         { *m = LabelSource{} }
func (m *LabelSource) String() string { return proto.CompactTextString(m) }
func (*LabelSource) ProtoMessage()    {}
func (*LabelSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{9}
}

func (m *LabelSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelSource.Unmarshal(m, b)
}
func (m *LabelSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelSource.Marshal(b, m, deterministic)
}
func (m *LabelSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelSource.Merge(m, src)
}
func (m *LabelSource) XXX_Size() int {
	return xxx_messageInfo_LabelSource.Size(m)
}
func (m *LabelSource) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelSource.DiscardUnknown(m)
}

var xxx_messageInfo_LabelSource proto.InternalMessageInfo

func (m *LabelSource) GetCatno() string {
	if m != nil {
		return m.Catno
	}
	return ""
}

func (m *LabelSource) GetEntityType() string {
	if m != nil {
		return m.EntityType
	}
	return ""
}

func (m *LabelSource) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LabelSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LabelSource) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

// Member ...
type Member struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ResourceUrl          string   `protobuf:"bytes,4,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{10}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Member) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Member) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

// Page ...
type Page struct {
	PerPage              int64     `protobuf:"varint,1,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Items                int64     `protobuf:"varint,2,opt,name=items,proto3" json:"items,omitempty"`
	Page                 int64     `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Urls                 *URLsList `protobuf:"bytes,4,opt,name=urls,proto3" json:"urls,omitempty"`
	Pages                int64     `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{11}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPerPage() int64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Page) GetItems() int64 {
	if m != nil {
		return m.Items
	}
	return 0
}

func (m *Page) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Page) GetUrls() *URLsList {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *Page) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

// Rating ...
type Rating struct {
	Average              float32  `protobuf:"fixed32,1,opt,name=average,proto3" json:"average,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rating) Reset()         { *m = Rating{} }
func (m *Rating) String() string { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()    {}
func (*Rating) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{12}
}

func (m *Rating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Rating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (m *Rating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(m, src)
}
func (m *Rating) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Rating) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Rating) GetAverage() float32 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *Rating) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// ReleaseSource ...
type ReleaseSource struct {
	Artist               string   `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Catno                string   `protobuf:"bytes,2,opt,name=catno,proto3" json:"catno,omitempty"`
	Format               string   `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	ResourceUrl          string   `protobuf:"bytes,5,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Thumb                string   `protobuf:"bytes,7,opt,name=thumb,proto3" json:"thumb,omitempty"`
	Title                string   `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Year                 int64    `protobuf:"varint,9,opt,name=year,proto3" json:"year,omitempty"`
	MainRelease          int64    `protobuf:"varint,10,opt,name=main_release,json=mainRelease,proto3" json:"main_release,omitempty"`
	Role                 string   `protobuf:"bytes,11,opt,name=role,proto3" json:"role,omitempty"`
	Type                 string   `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseSource) Reset()         { *m = ReleaseSource{} }
func (m *ReleaseSource) String() string { return proto.CompactTextString(m) }
func (*ReleaseSource) ProtoMessage()    {}
func (*ReleaseSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{13}
}

func (m *ReleaseSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseSource.Unmarshal(m, b)
}
func (m *ReleaseSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseSource.Marshal(b, m, deterministic)
}
func (m *ReleaseSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseSource.Merge(m, src)
}
func (m *ReleaseSource) XXX_Size() int {
	return xxx_messageInfo_ReleaseSource.Size(m)
}
func (m *ReleaseSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseSource.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseSource proto.InternalMessageInfo

func (m *ReleaseSource) GetArtist() string {
	if m != nil {
		return m.Artist
	}
	return ""
}

func (m *ReleaseSource) GetCatno() string {
	if m != nil {
		return m.Catno
	}
	return ""
}

func (m *ReleaseSource) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *ReleaseSource) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReleaseSource) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *ReleaseSource) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ReleaseSource) GetThumb() string {
	if m != nil {
		return m.Thumb
	}
	return ""
}

func (m *ReleaseSource) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ReleaseSource) GetYear() int64 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *ReleaseSource) GetMainRelease() int64 {
	if m != nil {
		return m.MainRelease
	}
	return 0
}

func (m *ReleaseSource) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ReleaseSource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// Result describes a part of search result
type Result struct {
	Style                []string   `protobuf:"bytes,1,rep,name=style,proto3" json:"style,omitempty"`
	Thumb                string     `protobuf:"bytes,2,opt,name=thumb,proto3" json:"thumb,omitempty"`
	Title                string     `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Country              string     `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Format               []string   `protobuf:"bytes,5,rep,name=format,proto3" json:"format,omitempty"`
	Uri                  string     `protobuf:"bytes,6,opt,name=uri,proto3" json:"uri,omitempty"`
	Community            *Community `protobuf:"bytes,7,opt,name=community,proto3" json:"community,omitempty"`
	Label                []string   `protobuf:"bytes,8,rep,name=label,proto3" json:"label,omitempty"`
	Catno                string     `protobuf:"bytes,9,opt,name=catno,proto3" json:"catno,omitempty"`
	Year                 string     `protobuf:"bytes,10,opt,name=year,proto3" json:"year,omitempty"`
	Genre                []string   `protobuf:"bytes,11,rep,name=genre,proto3" json:"genre,omitempty"`
	ResourceUrl          string     `protobuf:"bytes,12,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Type                 string     `protobuf:"bytes,13,opt,name=type,proto3" json:"type,omitempty"`
	Id                   int64      `protobuf:"varint,14,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{14}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetStyle() []string {
	if m != nil {
		return m.Style
	}
	return nil
}

func (m *Result) GetThumb() string {
	if m != nil {
		return m.Thumb
	}
	return ""
}

func (m *Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Result) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Result) GetFormat() []string {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *Result) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Result) GetCommunity() *Community {
	if m != nil {
		return m.Community
	}
	return nil
}

func (m *Result) GetLabel() []string {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *Result) GetCatno() string {
	if m != nil {
		return m.Catno
	}
	return ""
}

func (m *Result) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *Result) GetGenre() []string {
	if m != nil {
		return m.Genre
	}
	return nil
}

func (m *Result) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *Result) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Result) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// SearchService ...
type SearchService struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchService) Reset()         { *m = SearchService{} }
func (m *SearchService) String() string { return proto.CompactTextString(m) }
func (*SearchService) ProtoMessage()    {}
func (*SearchService) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{15}
}

func (m *SearchService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchService.Unmarshal(m, b)
}
func (m *SearchService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchService.Marshal(b, m, deterministic)
}
func (m *SearchService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchService.Merge(m, src)
}
func (m *SearchService) XXX_Size() int {
	return xxx_messageInfo_SearchService.Size(m)
}
func (m *SearchService) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchService.DiscardUnknown(m)
}

var xxx_messageInfo_SearchService proto.InternalMessageInfo

// Sublable ...
type Sublable struct {
	ResourceUrl          string   `protobuf:"bytes,1,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sublable) Reset()         { *m = Sublable{} }
func (m *Sublable) String() string { return proto.CompactTextString(m) }
func (*Sublable) ProtoMessage()    {}
func (*Sublable) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{16}
}

func (m *Sublable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sublable.Unmarshal(m, b)
}
func (m *Sublable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sublable.Marshal(b, m, deterministic)
}
func (m *Sublable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sublable.Merge(m, src)
}
func (m *Sublable) XXX_Size() int {
	return xxx_messageInfo_Sublable.Size(m)
}
func (m *Sublable) XXX_DiscardUnknown() {
	xxx_messageInfo_Sublable.DiscardUnknown(m)
}

var xxx_messageInfo_Sublable proto.InternalMessageInfo

func (m *Sublable) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *Sublable) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Sublable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Submitter ...
type Submitter struct {
	ResourceUrl          string   `protobuf:"bytes,1,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Submitter) Reset()         { *m = Submitter{} }
func (m *Submitter) String() string { return proto.CompactTextString(m) }
func (*Submitter) ProtoMessage()    {}
func (*Submitter) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{17}
}

func (m *Submitter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Submitter.Unmarshal(m, b)
}
func (m *Submitter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Submitter.Marshal(b, m, deterministic)
}
func (m *Submitter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Submitter.Merge(m, src)
}
func (m *Submitter) XXX_Size() int {
	return xxx_messageInfo_Submitter.Size(m)
}
func (m *Submitter) XXX_DiscardUnknown() {
	xxx_messageInfo_Submitter.DiscardUnknown(m)
}

var xxx_messageInfo_Submitter proto.InternalMessageInfo

func (m *Submitter) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *Submitter) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// Track ...
type Track struct {
	Duration             string          `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Position             string          `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Title                string          `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Type                 string          `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Extraartists         []*ArtistSource `protobuf:"bytes,5,rep,name=extraartists,proto3" json:"extraartists,omitempty"`
	Artists              []*ArtistSource `protobuf:"bytes,6,rep,name=artists,proto3" json:"artists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{18}
}

func (m *Track) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track.Unmarshal(m, b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track.Marshal(b, m, deterministic)
}
func (m *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(m, src)
}
func (m *Track) XXX_Size() int {
	return xxx_messageInfo_Track.Size(m)
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *Track) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Track) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Track) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Track) GetExtraartists() []*ArtistSource {
	if m != nil {
		return m.Extraartists
	}
	return nil
}

func (m *Track) GetArtists() []*ArtistSource {
	if m != nil {
		return m.Artists
	}
	return nil
}

// URLsList ...
type URLsList struct {
	Last                 string   `protobuf:"bytes,1,opt,name=last,proto3" json:"last,omitempty"`
	Next                 string   `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URLsList) Reset()         { *m = URLsList{} }
func (m *URLsList) String() string { return proto.CompactTextString(m) }
func (*URLsList) ProtoMessage()    {}
func (*URLsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{19}
}

func (m *URLsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URLsList.Unmarshal(m, b)
}
func (m *URLsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URLsList.Marshal(b, m, deterministic)
}
func (m *URLsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URLsList.Merge(m, src)
}
func (m *URLsList) XXX_Size() int {
	return xxx_messageInfo_URLsList.Size(m)
}
func (m *URLsList) XXX_DiscardUnknown() {
	xxx_messageInfo_URLsList.DiscardUnknown(m)
}

var xxx_messageInfo_URLsList proto.InternalMessageInfo

func (m *URLsList) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func (m *URLsList) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

// Version ...
type Version struct {
	Catno                string   `protobuf:"bytes,1,opt,name=catno,proto3" json:"catno,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Format               string   `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Label                string   `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Released             string   `protobuf:"bytes,6,opt,name=released,proto3" json:"released,omitempty"`
	ResourceUrl          string   `protobuf:"bytes,7,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	Status               string   `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Thumb                string   `protobuf:"bytes,9,opt,name=thumb,proto3" json:"thumb,omitempty"`
	Title                string   `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{20}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetCatno() string {
	if m != nil {
		return m.Catno
	}
	return ""
}

func (m *Version) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Version) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Version) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Version) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Version) GetReleased() string {
	if m != nil {
		return m.Released
	}
	return ""
}

func (m *Version) GetResourceUrl() string {
	if m != nil {
		return m.ResourceUrl
	}
	return ""
}

func (m *Version) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Version) GetThumb() string {
	if m != nil {
		return m.Thumb
	}
	return ""
}

func (m *Version) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// Video ...
type Video struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Duration             int64    `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Embed                bool     `protobuf:"varint,3,opt,name=embed,proto3" json:"embed,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Uri                  string   `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{21}
}

func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (m *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(m, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Video) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Video) GetEmbed() bool {
	if m != nil {
		return m.Embed
	}
	return false
}

func (m *Video) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Video) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type ListParams struct {
	Artist               string   `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListParams) Reset()         { *m = ListParams{} }
func (m *ListParams) String() string { return proto.CompactTextString(m) }
func (*ListParams) ProtoMessage()    {}
func (*ListParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{22}
}

func (m *ListParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListParams.Unmarshal(m, b)
}
func (m *ListParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListParams.Marshal(b, m, deterministic)
}
func (m *ListParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListParams.Merge(m, src)
}
func (m *ListParams) XXX_Size() int {
	return xxx_messageInfo_ListParams.Size(m)
}
func (m *ListParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListParams.DiscardUnknown(m)
}

var xxx_messageInfo_ListParams proto.InternalMessageInfo

func (m *ListParams) GetArtist() string {
	if m != nil {
		return m.Artist
	}
	return ""
}

func (m *ListParams) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ListParams) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type GetParams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParams) Reset()         { *m = GetParams{} }
func (m *GetParams) String() string { return proto.CompactTextString(m) }
func (*GetParams) ProtoMessage()    {}
func (*GetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{23}
}

func (m *GetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParams.Unmarshal(m, b)
}
func (m *GetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParams.Marshal(b, m, deterministic)
}
func (m *GetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParams.Merge(m, src)
}
func (m *GetParams) XXX_Size() int {
	return xxx_messageInfo_GetParams.Size(m)
}
func (m *GetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetParams proto.InternalMessageInfo

func (m *GetParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SearchParams struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ReleaseTitle         string   `protobuf:"bytes,4,opt,name=releaseTitle,proto3" json:"releaseTitle,omitempty"`
	Credit               string   `protobuf:"bytes,5,opt,name=credit,proto3" json:"credit,omitempty"`
	Artist               string   `protobuf:"bytes,6,opt,name=artist,proto3" json:"artist,omitempty"`
	Anv                  string   `protobuf:"bytes,7,opt,name=anv,proto3" json:"anv,omitempty"`
	Label                string   `protobuf:"bytes,8,opt,name=label,proto3" json:"label,omitempty"`
	Genre                string   `protobuf:"bytes,9,opt,name=genre,proto3" json:"genre,omitempty"`
	Country              string   `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	Year                 string   `protobuf:"bytes,11,opt,name=year,proto3" json:"year,omitempty"`
	Format               string   `protobuf:"bytes,12,opt,name=format,proto3" json:"format,omitempty"`
	Catno                string   `protobuf:"bytes,13,opt,name=catno,proto3" json:"catno,omitempty"`
	Barcode              string   `protobuf:"bytes,14,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Track                string   `protobuf:"bytes,15,opt,name=track,proto3" json:"track,omitempty"`
	Submitter            string   `protobuf:"bytes,16,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Contributor          string   `protobuf:"bytes,17,opt,name=contributor,proto3" json:"contributor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchParams) Reset()         { *m = SearchParams{} }
func (m *SearchParams) String() string { return proto.CompactTextString(m) }
func (*SearchParams) ProtoMessage()    {}
func (*SearchParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{24}
}

func (m *SearchParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchParams.Unmarshal(m, b)
}
func (m *SearchParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchParams.Marshal(b, m, deterministic)
}
func (m *SearchParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchParams.Merge(m, src)
}
func (m *SearchParams) XXX_Size() int {
	return xxx_messageInfo_SearchParams.Size(m)
}
func (m *SearchParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchParams.DiscardUnknown(m)
}

var xxx_messageInfo_SearchParams proto.InternalMessageInfo

func (m *SearchParams) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchParams) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchParams) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchParams) GetReleaseTitle() string {
	if m != nil {
		return m.ReleaseTitle
	}
	return ""
}

func (m *SearchParams) GetCredit() string {
	if m != nil {
		return m.Credit
	}
	return ""
}

func (m *SearchParams) GetArtist() string {
	if m != nil {
		return m.Artist
	}
	return ""
}

func (m *SearchParams) GetAnv() string {
	if m != nil {
		return m.Anv
	}
	return ""
}

func (m *SearchParams) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *SearchParams) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func (m *SearchParams) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *SearchParams) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *SearchParams) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *SearchParams) GetCatno() string {
	if m != nil {
		return m.Catno
	}
	return ""
}

func (m *SearchParams) GetBarcode() string {
	if m != nil {
		return m.Barcode
	}
	return ""
}

func (m *SearchParams) GetTrack() string {
	if m != nil {
		return m.Track
	}
	return ""
}

func (m *SearchParams) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *SearchParams) GetContributor() string {
	if m != nil {
		return m.Contributor
	}
	return ""
}

type StoreParams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreParams) Reset()         { *m = StoreParams{} }
func (m *StoreParams) String() string { return proto.CompactTextString(m) }
func (*StoreParams) ProtoMessage()    {}
func (*StoreParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{25}
}

func (m *StoreParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreParams.Unmarshal(m, b)
}
func (m *StoreParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreParams.Marshal(b, m, deterministic)
}
func (m *StoreParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreParams.Merge(m, src)
}
func (m *StoreParams) XXX_Size() int {
	return xxx_messageInfo_StoreParams.Size(m)
}
func (m *StoreParams) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreParams.DiscardUnknown(m)
}

var xxx_messageInfo_StoreParams proto.InternalMessageInfo

func (m *StoreParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type HealthRequest struct {
	Uptime               string   `protobuf:"bytes,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Machine              string   `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{26}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

func (m *HealthRequest) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *HealthRequest) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

type HealthResponse struct {
	Uptime               string   `protobuf:"bytes,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Machine              string   `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{27}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *HealthResponse) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

type BadRequest struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadRequest) Reset()         { *m = BadRequest{} }
func (m *BadRequest) String() string { return proto.CompactTextString(m) }
func (*BadRequest) ProtoMessage()    {}
func (*BadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cbfdf35f94f117e, []int{28}
}

func (m *BadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadRequest.Unmarshal(m, b)
}
func (m *BadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadRequest.Marshal(b, m, deterministic)
}
func (m *BadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadRequest.Merge(m, src)
}
func (m *BadRequest) XXX_Size() int {
	return xxx_messageInfo_BadRequest.Size(m)
}
func (m *BadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BadRequest proto.InternalMessageInfo

func (m *BadRequest) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BadRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Artist)(nil), "vinyl.Artist")
	proto.RegisterType((*ArtistSource)(nil), "vinyl.ArtistSource")
	proto.RegisterType((*Community)(nil), "vinyl.Community")
	proto.RegisterType((*Company)(nil), "vinyl.Company")
	proto.RegisterType((*Contributor)(nil), "vinyl.Contributor")
	proto.RegisterType((*DatabaseService)(nil), "vinyl.DatabaseService")
	proto.RegisterType((*Format)(nil), "vinyl.Format")
	proto.RegisterType((*Identifier)(nil), "vinyl.Identifier")
	proto.RegisterType((*Image)(nil), "vinyl.Image")
	proto.RegisterType((*LabelSource)(nil), "vinyl.LabelSource")
	proto.RegisterType((*Member)(nil), "vinyl.Member")
	proto.RegisterType((*Page)(nil), "vinyl.Page")
	proto.RegisterType((*Rating)(nil), "vinyl.Rating")
	proto.RegisterType((*ReleaseSource)(nil), "vinyl.ReleaseSource")
	proto.RegisterType((*Result)(nil), "vinyl.Result")
	proto.RegisterType((*SearchService)(nil), "vinyl.SearchService")
	proto.RegisterType((*Sublable)(nil), "vinyl.Sublable")
	proto.RegisterType((*Submitter)(nil), "vinyl.Submitter")
	proto.RegisterType((*Track)(nil), "vinyl.Track")
	proto.RegisterType((*URLsList)(nil), "vinyl.URLsList")
	proto.RegisterType((*Version)(nil), "vinyl.Version")
	proto.RegisterType((*Video)(nil), "vinyl.Video")
	proto.RegisterType((*ListParams)(nil), "vinyl.ListParams")
	proto.RegisterType((*GetParams)(nil), "vinyl.GetParams")
	proto.RegisterType((*SearchParams)(nil), "vinyl.SearchParams")
	proto.RegisterType((*StoreParams)(nil), "vinyl.StoreParams")
	proto.RegisterType((*HealthRequest)(nil), "vinyl.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "vinyl.HealthResponse")
	proto.RegisterType((*BadRequest)(nil), "vinyl.BadRequest")
}

func init() { proto.RegisterFile("vinyl.proto", fileDescriptor_1cbfdf35f94f117e) }

var fileDescriptor_1cbfdf35f94f117e = []byte{
	// 2296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0xcd, 0x6f, 0x23, 0x49,
	0x15, 0x9f, 0xf6, 0x47, 0xdb, 0x7e, 0x76, 0x32, 0x99, 0x9a, 0x64, 0xe5, 0xf5, 0xce, 0x6c, 0x7a,
	0x0d, 0x2c, 0xd9, 0xec, 0x4c, 0x9c, 0x64, 0x66, 0x24, 0x88, 0x16, 0xb4, 0xce, 0x0c, 0x3b, 0x44,
	0xcc, 0xae, 0x66, 0x3b, 0x93, 0x95, 0x58, 0x21, 0x45, 0xe5, 0xee, 0x8a, 0x5d, 0xb3, 0xed, 0x6e,
	0x4f, 0x55, 0xb5, 0x67, 0xcc, 0x0a, 0x21, 0x21, 0x0e, 0x7b, 0x84, 0xc0, 0x89, 0x0b, 0x8b, 0x04,
	0x27, 0xb8, 0xf2, 0x0f, 0x70, 0xe2, 0x8a, 0xb8, 0x80, 0x90, 0x22, 0x14, 0x90, 0xb8, 0x70, 0xe0,
	0xcc, 0x05, 0x54, 0x1f, 0x6d, 0x97, 0xe3, 0x78, 0xbe, 0x10, 0xa7, 0xd4, 0x7b, 0xf5, 0xaa, 0xea,
	0xd5, 0x7b, 0xbf, 0xfa, 0xbd, 0xd7, 0x0e, 0x54, 0x87, 0x34, 0x1e, 0x45, 0x1b, 0x03, 0x96, 0x88,
	0x04, 0x15, 0x95, 0xd0, 0xb8, 0xde, 0xa5, 0xa2, 0x97, 0x76, 0x36, 0x82, 0xa4, 0xdf, 0xea, 0x26,
	0xdd, 0xa4, 0xa5, 0x66, 0x3b, 0xe9, 0x91, 0x92, 0x94, 0xa0, 0x46, 0x7a, 0x55, 0xe3, 0x4a, 0x37,
	0x49, 0xba, 0x11, 0x69, 0xe1, 0x01, 0x6d, 0xe1, 0x38, 0x4e, 0x04, 0x16, 0x34, 0x89, 0xb9, 0x99,
	0xbd, 0xa6, 0xfe, 0x04, 0xd7, 0xbb, 0x24, 0xbe, 0xce, 0x1f, 0xe3, 0x6e, 0x97, 0xb0, 0x56, 0x32,
	0x50, 0x16, 0xb3, 0xd6, 0xcd, 0xe3, 0x3c, 0xb8, 0x6d, 0x26, 0x28, 0x17, 0xe8, 0x4d, 0x58, 0x8c,
	0x71, 0x9f, 0x0c, 0x31, 0xa3, 0xda, 0xa4, 0xee, 0x78, 0xf9, 0xb5, 0x8a, 0x7f, 0x46, 0x8b, 0xea,
	0x50, 0x1a, 0xb0, 0xe4, 0x88, 0x46, 0xa4, 0x9e, 0xf3, 0x9c, 0xb5, 0x8a, 0x9f, 0x89, 0x68, 0x1b,
	0x6a, 0x8c, 0x44, 0x04, 0x73, 0xc2, 0x0f, 0x53, 0x16, 0xd5, 0xf3, 0x72, 0x7a, 0xf7, 0xe2, 0xe9,
	0xc9, 0x6a, 0xd5, 0x37, 0xfa, 0x03, 0xff, 0x9e, 0x5f, 0xcd, 0x8c, 0x0e, 0x58, 0xa4, 0xd7, 0xf0,
	0x24, 0x65, 0x01, 0x51, 0x6b, 0x0a, 0xf6, 0x1a, 0xad, 0x37, 0x6b, 0x8c, 0xc0, 0x22, 0xf4, 0x2a,
	0xe4, 0x53, 0x46, 0xeb, 0x45, 0x65, 0x5a, 0x3a, 0x3d, 0x59, 0xcd, 0x1f, 0xf8, 0x7b, 0xbe, 0xd4,
	0xa1, 0x2b, 0x50, 0x48, 0x59, 0xc4, 0xeb, 0xae, 0x74, 0x7d, 0xb7, 0x7c, 0x7a, 0xb2, 0x5a, 0x38,
	0xf0, 0xef, 0x71, 0x5f, 0x69, 0xd1, 0x1b, 0x50, 0x0b, 0xb1, 0xc0, 0x87, 0x8f, 0x52, 0x1c, 0x51,
	0x31, 0xaa, 0x97, 0x94, 0xff, 0x55, 0xa9, 0xfb, 0x50, 0xab, 0xd0, 0x55, 0xc8, 0xd1, 0xb0, 0x5e,
	0xf6, 0x9c, 0xb5, 0xfc, 0xee, 0xc2, 0xe9, 0xc9, 0x6a, 0x6e, 0xef, 0xce, 0xbf, 0x4f, 0x56, 0xf3,
	0x34, 0x16, 0x7e, 0x8e, 0x86, 0x68, 0x1d, 0x5c, 0xda, 0xc7, 0x5d, 0xc2, 0xeb, 0x15, 0x2f, 0xbf,
	0x56, 0xdd, 0xae, 0x6d, 0xe8, 0x7c, 0xee, 0x49, 0xe5, 0x6e, 0xe1, 0xf7, 0x27, 0xab, 0x17, 0x7c,
	0x63, 0x81, 0xae, 0x43, 0xa9, 0x4f, 0xfa, 0x1d, 0xc2, 0x78, 0x1d, 0x94, 0xf1, 0x82, 0x31, 0x7e,
	0x5f, 0x69, 0x8d, 0x75, 0x66, 0xb3, 0x53, 0xfe, 0xec, 0xf3, 0xd5, 0x0b, 0xff, 0xfa, 0xc5, 0xea,
	0x85, 0xe6, 0x1f, 0x1c, 0xa8, 0xe9, 0xa4, 0xec, 0xab, 0x3b, 0xa3, 0x25, 0xc8, 0xe3, 0x78, 0x58,
	0x77, 0x94, 0xbb, 0x72, 0x68, 0xdc, 0xcc, 0xcd, 0x73, 0x13, 0x41, 0xe1, 0x61, 0x42, 0x63, 0x9d,
	0x01, 0x5f, 0x8d, 0xa5, 0x4e, 0x66, 0x52, 0x47, 0xd8, 0x57, 0xe3, 0x99, 0xe8, 0x17, 0x9f, 0x23,
	0xfa, 0x08, 0x0a, 0x2c, 0x89, 0x48, 0xdd, 0xd5, 0xfb, 0xc8, 0x31, 0x7a, 0x05, 0x5c, 0xc1, 0x70,
	0xf0, 0x09, 0x37, 0x21, 0x35, 0x92, 0x75, 0xa7, 0x5f, 0xe7, 0xa0, 0x72, 0x3b, 0xe9, 0xf7, 0xd3,
	0x58, 0x46, 0xf9, 0x1d, 0xa8, 0x05, 0x49, 0x2c, 0x18, 0xed, 0xa4, 0x22, 0x61, 0x1a, 0x69, 0xd5,
	0x6d, 0x64, 0xe2, 0x73, 0x7b, 0x32, 0x65, 0x82, 0x34, 0x65, 0x3d, 0x93, 0xc6, 0xdc, 0x6c, 0x1a,
	0x5f, 0x83, 0x42, 0x0f, 0x0f, 0x89, 0x0a, 0x40, 0x7e, 0xb7, 0x94, 0xc5, 0x46, 0x29, 0xd1, 0xdb,
	0xe0, 0x32, 0x2c, 0x68, 0xdc, 0x55, 0xb1, 0x98, 0xe4, 0xc5, 0x57, 0xca, 0x2c, 0x8b, 0xda, 0x44,
	0x5e, 0x8d, 0x0b, 0x2c, 0x52, 0xae, 0x83, 0xe3, 0x1b, 0x09, 0xdd, 0x84, 0x0a, 0x4f, 0x3b, 0x7d,
	0x2a, 0x04, 0x61, 0x2a, 0x16, 0xd5, 0xed, 0x25, 0xb3, 0xcf, 0x7e, 0xa6, 0x37, 0x5b, 0x4d, 0x0c,
	0xa5, 0x5f, 0x8f, 0x71, 0x2c, 0x54, 0x98, 0x6c, 0xbf, 0xa4, 0xd2, 0x8a, 0xd6, 0x5f, 0x1c, 0x28,
	0xdd, 0x4e, 0xfa, 0x03, 0x1c, 0x8f, 0xd0, 0x32, 0x14, 0x03, 0x2c, 0xe2, 0xc4, 0xa4, 0x5f, 0x0b,
	0x68, 0x15, 0xaa, 0x24, 0x16, 0x54, 0x8c, 0x0e, 0xc5, 0x68, 0x90, 0xbd, 0x44, 0xd0, 0xaa, 0x07,
	0xa3, 0x01, 0x41, 0x6b, 0xb0, 0x64, 0x19, 0x1c, 0xaa, 0xd4, 0x6b, 0x38, 0x2c, 0x4e, 0xac, 0x3e,
	0x90, 0x20, 0xd0, 0x58, 0x2a, 0x3c, 0x05, 0x4b, 0x6a, 0x71, 0xf1, 0x29, 0xb8, 0x71, 0x9f, 0x8d,
	0x1b, 0xeb, 0x76, 0x5d, 0xa8, 0x5a, 0x29, 0x9e, 0xd9, 0xcc, 0x79, 0x0e, 0x10, 0x36, 0xa0, 0x9c,
	0x72, 0xc2, 0x94, 0x63, 0xfa, 0xee, 0x63, 0xd9, 0x3a, 0xe8, 0x35, 0xb8, 0x78, 0x07, 0x0b, 0xdc,
	0xc1, 0x9c, 0xec, 0x13, 0x36, 0xa4, 0x81, 0x3d, 0xf9, 0x1d, 0x70, 0xdf, 0x4b, 0x58, 0x1f, 0x0b,
	0xd4, 0x84, 0x5a, 0x48, 0x78, 0xc0, 0xe8, 0xc0, 0xe6, 0xbd, 0x29, 0xdd, 0x38, 0x0a, 0x39, 0x2b,
	0x0a, 0x4b, 0x90, 0x7f, 0x24, 0x46, 0x26, 0xaa, 0x72, 0x68, 0xed, 0xfe, 0x2e, 0xc0, 0x5e, 0x28,
	0x03, 0x7d, 0x44, 0x09, 0x93, 0xab, 0x55, 0x9a, 0x74, 0x0a, 0xd5, 0x58, 0xe6, 0x75, 0x88, 0xa3,
	0x34, 0xdb, 0x52, 0x0b, 0xd6, 0x0e, 0x7f, 0x72, 0xa0, 0xa8, 0x68, 0x05, 0xad, 0x82, 0xdb, 0x23,
	0xb4, 0xdb, 0x13, 0x6a, 0xbd, 0x05, 0x1b, 0xa3, 0x46, 0x57, 0xa1, 0xf8, 0x98, 0x86, 0xa2, 0x67,
	0x08, 0x61, 0x3c, 0xaf, 0xb5, 0x33, 0x01, 0xce, 0x3f, 0xdf, 0x2b, 0x57, 0x1e, 0x17, 0x2c, 0x8f,
	0x9f, 0xc2, 0xbb, 0x4d, 0x70, 0x53, 0x46, 0xb7, 0x6e, 0x6d, 0x1a, 0x28, 0xc0, 0xe9, 0xc9, 0xaa,
	0x7b, 0xe0, 0xef, 0x6d, 0xdd, 0xda, 0xf4, 0xcd, 0x8c, 0x75, 0xb5, 0xdf, 0x3a, 0x50, 0xbd, 0x87,
	0x3b, 0x24, 0x32, 0xfc, 0xf6, 0x92, 0x10, 0xd7, 0xc0, 0xcd, 0x3f, 0x0b, 0xb8, 0xff, 0x23, 0xe1,
	0x59, 0x7e, 0xff, 0xd8, 0x01, 0x57, 0x93, 0xb7, 0xa4, 0x05, 0x1c, 0x08, 0x3a, 0xd4, 0x39, 0x2d,
	0xfb, 0x46, 0x7a, 0x0e, 0x62, 0xb6, 0x5e, 0xe2, 0xf9, 0x3e, 0x15, 0x5e, 0xc8, 0xa7, 0xdf, 0x39,
	0x50, 0xb8, 0x2f, 0x51, 0xd2, 0x84, 0xf2, 0x80, 0xb0, 0xc3, 0x01, 0xee, 0x92, 0xb3, 0x38, 0x29,
	0x0d, 0x08, 0x53, 0x36, 0x57, 0xa1, 0x48, 0x05, 0xe9, 0xf3, 0x19, 0xa0, 0x28, 0xad, 0x64, 0x27,
	0xb5, 0xfc, 0x2c, 0x6b, 0x4a, 0x25, 0xda, 0x32, 0xa5, 0x55, 0x73, 0xe6, 0x45, 0xc3, 0x75, 0xb2,
	0xba, 0xde, 0xa3, 0x5c, 0xec, 0xd6, 0x24, 0xd5, 0x9d, 0xa9, 0xb7, 0x57, 0xa1, 0x38, 0x50, 0xc5,
	0xb2, 0x78, 0xe6, 0x38, 0xa5, 0xb5, 0x2e, 0xf1, 0x2d, 0x70, 0x35, 0xf9, 0xca, 0xee, 0x02, 0x0f,
	0x09, 0xcb, 0x2e, 0x91, 0xf3, 0x33, 0x51, 0x6e, 0x16, 0x24, 0x69, 0x2c, 0x66, 0x7c, 0x57, 0x5a,
	0x6b, 0xb3, 0xff, 0xe4, 0x60, 0xc1, 0xf4, 0x1b, 0x06, 0x5f, 0x32, 0x59, 0xaa, 0x9e, 0x1a, 0x80,
	0x19, 0x69, 0x82, 0xbb, 0x9c, 0x8d, 0xbb, 0x57, 0xc0, 0x3d, 0x52, 0xc4, 0x60, 0xb2, 0x64, 0xa4,
	0x67, 0xf1, 0xe4, 0xcb, 0xd4, 0xd2, 0x49, 0x71, 0x71, 0xa7, 0x8a, 0xcb, 0x32, 0x14, 0x45, 0x2f,
	0xed, 0x77, 0x4c, 0x39, 0xd5, 0x82, 0xd2, 0x52, 0x11, 0x11, 0xd5, 0x9e, 0x48, 0xad, 0x14, 0x64,
	0xd2, 0x46, 0x04, 0xb3, 0x7a, 0xe5, 0x4c, 0xd2, 0xa4, 0x12, 0xad, 0x43, 0xad, 0x8f, 0x69, 0x7c,
	0x68, 0x5a, 0xae, 0x3a, 0x4c, 0x1b, 0x55, 0xe5, 0xa4, 0x89, 0xd5, 0xb8, 0xb0, 0x57, 0xad, 0xc2,
	0x9e, 0xd1, 0x40, 0x6d, 0x42, 0x03, 0x3b, 0xde, 0x71, 0x7b, 0x05, 0x2e, 0xaf, 0x4f, 0xc7, 0xf8,
	0x67, 0x39, 0xc7, 0x1d, 0x67, 0xe0, 0xa7, 0x79, 0x70, 0x7d, 0xc2, 0xd3, 0x48, 0x85, 0x98, 0x8b,
	0x51, 0x44, 0x0c, 0xa9, 0x6a, 0x61, 0x72, 0xbf, 0xdc, 0xb9, 0xf7, 0xcb, 0xdb, 0xf7, 0xab, 0x43,
	0x49, 0x65, 0x98, 0x8d, 0xcc, 0x4b, 0xce, 0x44, 0x2b, 0x51, 0x45, 0xb5, 0x79, 0x96, 0x28, 0xc3,
	0x53, 0xee, 0x39, 0x3c, 0x75, 0x13, 0x2a, 0x41, 0xd6, 0x85, 0xa8, 0xe0, 0x4e, 0xaa, 0xf6, 0xb8,
	0x3b, 0xc9, 0xaa, 0xf6, 0xd8, 0x50, 0x3a, 0x16, 0x49, 0xba, 0xaa, 0x97, 0xf5, 0x25, 0x94, 0x30,
	0x41, 0x4f, 0xc5, 0x46, 0x0f, 0x32, 0xe9, 0x00, 0x1d, 0x31, 0x95, 0x85, 0x65, 0x28, 0x76, 0x49,
	0xcc, 0x64, 0x68, 0xd5, 0x7a, 0x25, 0xcc, 0x00, 0xa6, 0xf6, 0x02, 0xb4, 0xbc, 0x60, 0xd1, 0xb2,
	0xc6, 0xe5, 0xe2, 0x1c, 0x5c, 0x5a, 0x0f, 0xe3, 0x55, 0x58, 0xd8, 0x27, 0x98, 0x05, 0xbd, 0xd9,
	0x62, 0xf8, 0x29, 0x94, 0xf7, 0xd3, 0x4e, 0x84, 0x3b, 0x11, 0x79, 0xa9, 0x7a, 0xfc, 0xe2, 0xb4,
	0x67, 0x1d, 0x4e, 0xa0, 0x32, 0x6e, 0x99, 0xfe, 0x8f, 0xdd, 0xc0, 0x3f, 0x1c, 0x28, 0x3e, 0x90,
	0x7d, 0xa9, 0xb4, 0x0f, 0x53, 0xa6, 0xbe, 0x67, 0x0c, 0x23, 0x8c, 0x65, 0x39, 0x37, 0x48, 0x38,
	0x55, 0x73, 0x66, 0xaf, 0x4c, 0x9e, 0x03, 0xd0, 0xf3, 0x4a, 0xe5, 0xd7, 0xa0, 0x46, 0x9e, 0x08,
	0x86, 0x35, 0xd1, 0x70, 0x05, 0xd0, 0xea, 0xf6, 0x65, 0x03, 0x35, 0xbb, 0xb9, 0xcf, 0x3a, 0x5c,
	0xdb, 0x1c, 0xdd, 0x80, 0x52, 0xb6, 0xd2, 0x7d, 0xd6, 0xca, 0xcc, 0xd2, 0xba, 0xe9, 0x3b, 0x50,
	0xce, 0x78, 0x59, 0x7a, 0x17, 0xe1, 0x31, 0xf3, 0xa9, 0xb1, 0x4a, 0x07, 0x79, 0x22, 0xc6, 0xcd,
	0x0c, 0x79, 0x62, 0xf3, 0xe7, 0x2f, 0x73, 0x50, 0xfa, 0x88, 0x30, 0x6e, 0x6e, 0x7c, 0x4e, 0x65,
	0xb6, 0x9e, 0x64, 0x6e, 0xde, 0x93, 0x7c, 0x21, 0xee, 0x1c, 0x3f, 0x30, 0xdd, 0x64, 0x9a, 0x07,
	0xd6, 0x80, 0xb2, 0xe1, 0xad, 0xd0, 0xf0, 0xe3, 0x58, 0x9e, 0x81, 0x49, 0xe9, 0x85, 0xd8, 0xb6,
	0x7c, 0x3e, 0xdb, 0x56, 0xce, 0x65, 0x23, 0xb0, 0x92, 0x6d, 0x85, 0xe9, 0xe7, 0x0e, 0x14, 0x3f,
	0xa2, 0x21, 0x49, 0x90, 0x07, 0x55, 0xab, 0x57, 0x34, 0xa1, 0xb2, 0x55, 0xe8, 0x0b, 0x16, 0xe0,
	0xce, 0x94, 0xaf, 0x09, 0xf2, 0x96, 0xa1, 0x28, 0x7b, 0x0b, 0xdd, 0xd1, 0x94, 0x7d, 0x2d, 0x4c,
	0xdc, 0x28, 0xd8, 0x98, 0x9b, 0xdf, 0x8a, 0x59, 0x1e, 0x7e, 0x00, 0x20, 0x21, 0x70, 0x1f, 0x33,
	0xdc, 0xe7, 0x73, 0x8b, 0x60, 0x06, 0xdf, 0xdc, 0x74, 0x6f, 0x3a, 0x0b, 0xf4, 0xe6, 0x6b, 0x50,
	0xb9, 0x4b, 0xb2, 0xed, 0x16, 0x55, 0x46, 0xf5, 0x56, 0x39, 0x1a, 0x36, 0x7f, 0x93, 0x87, 0x9a,
	0x66, 0x17, 0x63, 0xb0, 0x0c, 0xc5, 0x47, 0x29, 0x61, 0xa3, 0x0c, 0x3a, 0x4a, 0x78, 0xfe, 0xd3,
	0x64, 0x57, 0x6e, 0xb2, 0xfd, 0xc0, 0xba, 0xff, 0x94, 0x4e, 0xde, 0x29, 0x60, 0x24, 0xa4, 0x22,
	0xfb, 0x38, 0xd3, 0x92, 0x75, 0x57, 0x77, 0xea, 0xae, 0xe6, 0x43, 0xba, 0x34, 0xf9, 0x90, 0xb6,
	0xa8, 0xdd, 0x99, 0xa2, 0x76, 0x4d, 0xd8, 0x06, 0x11, 0x9a, 0xb0, 0x2d, 0xd8, 0xc3, 0x34, 0xec,
	0x33, 0xd2, 0xaf, 0x5a, 0xa4, 0x3f, 0x79, 0x0a, 0xb5, 0xa9, 0xa7, 0x30, 0x7e, 0x52, 0x0b, 0x67,
	0x9e, 0x54, 0x07, 0xb3, 0x20, 0x09, 0x89, 0x62, 0xf2, 0x8a, 0x9f, 0x89, 0x2a, 0x3a, 0x92, 0xb5,
	0xea, 0x17, 0x4d, 0x74, 0x14, 0x85, 0x5d, 0xb1, 0x3f, 0x3f, 0x97, 0xd4, 0x8c, 0xf5, 0x99, 0xe9,
	0x41, 0xd5, 0xfa, 0x62, 0xae, 0x5f, 0xd2, 0x88, 0xb4, 0x54, 0xcd, 0xab, 0x50, 0xdd, 0x17, 0x09,
	0x23, 0x73, 0xb2, 0xd9, 0x86, 0x85, 0x6f, 0x12, 0x1c, 0x89, 0x9e, 0x4f, 0x1e, 0xa5, 0x84, 0xab,
	0x88, 0xa6, 0x03, 0x41, 0xfb, 0xd9, 0x37, 0x8c, 0x91, 0xa4, 0xdf, 0x7d, 0x1c, 0xf4, 0x68, 0x3c,
	0xfe, 0x35, 0xc8, 0x88, 0xcd, 0x5d, 0x58, 0xcc, 0xb6, 0xe0, 0x83, 0x24, 0xe6, 0xe4, 0x25, 0xf6,
	0xf8, 0x10, 0x60, 0x17, 0x87, 0x99, 0x0f, 0x08, 0x0a, 0x2a, 0x40, 0xaa, 0xbb, 0xf5, 0xd5, 0x58,
	0xad, 0x25, 0x9c, 0xcb, 0x7e, 0x31, 0x5b, 0xab, 0xc5, 0x9d, 0x95, 0xe3, 0x36, 0x82, 0xa5, 0x75,
	0x6b, 0x03, 0xd9, 0xa3, 0x6c, 0xff, 0xaa, 0x28, 0x9f, 0x6d, 0x3c, 0x8a, 0xd0, 0x0f, 0x1d, 0x70,
	0xb5, 0x87, 0x68, 0xd9, 0xd0, 0xeb, 0xd4, 0x9d, 0x1b, 0x2b, 0x67, 0xb4, 0xfa, 0x1a, 0xcd, 0xf7,
	0x8f, 0xdb, 0x5f, 0x41, 0x35, 0xad, 0xf4, 0x6e, 0xf7, 0x48, 0xf0, 0x49, 0x63, 0xcd, 0x27, 0x22,
	0x65, 0x31, 0xf7, 0x44, 0x8f, 0x78, 0x41, 0xca, 0x18, 0x89, 0x85, 0x27, 0xd9, 0x85, 0x78, 0xc9,
	0x91, 0x52, 0x72, 0x5d, 0x72, 0x7f, 0xf0, 0xc7, 0xbf, 0xff, 0x24, 0x57, 0x43, 0xd0, 0x1a, 0x6e,
	0xb6, 0x7a, 0xfa, 0xec, 0x21, 0x14, 0x14, 0x51, 0x5f, 0x32, 0xa7, 0x4d, 0x9e, 0x6c, 0x23, 0x73,
	0x6b, 0xaa, 0xd3, 0x6a, 0xde, 0x3e, 0x6e, 0x6f, 0xa1, 0x95, 0xbb, 0x44, 0x78, 0x3e, 0xe9, 0x52,
	0x2e, 0x08, 0x23, 0xa1, 0xa7, 0xae, 0xc4, 0x1b, 0xf5, 0xb6, 0x17, 0x51, 0x2e, 0xe4, 0xa9, 0x6a,
	0xa9, 0x97, 0x74, 0x1e, 0x92, 0x40, 0xf0, 0x0d, 0x75, 0x70, 0x05, 0x95, 0x5a, 0x4a, 0xcd, 0x37,
	0x1d, 0xf4, 0x7d, 0xc8, 0xdf, 0x25, 0x02, 0x65, 0xed, 0xcf, 0xf8, 0x65, 0xcf, 0x39, 0xf5, 0xfe,
	0x71, 0xfb, 0xab, 0x68, 0x59, 0x9e, 0x8a, 0xb3, 0x73, 0xcd, 0xa9, 0x8d, 0x37, 0x7c, 0x22, 0x18,
	0x25, 0x43, 0xe2, 0x61, 0x8f, 0x0f, 0x48, 0x40, 0x8f, 0x68, 0x30, 0x75, 0xbc, 0x3e, 0x7d, 0x11,
	0xd5, 0xcc, 0xe9, 0xad, 0x4f, 0x69, 0xf8, 0x3d, 0xf4, 0x23, 0x07, 0x5c, 0xcd, 0x18, 0x28, 0x2b,
	0x6f, 0x36, 0x81, 0xcc, 0xf1, 0xe3, 0xdb, 0xc7, 0xed, 0x3b, 0xe8, 0x4d, 0x6d, 0xe8, 0x1d, 0x25,
	0x4c, 0x1f, 0x24, 0x23, 0x8f, 0x85, 0x87, 0x19, 0xf1, 0x42, 0xca, 0x35, 0xca, 0x49, 0xd8, 0x68,
	0x58, 0x76, 0xd8, 0xb8, 0x64, 0x08, 0x44, 0x67, 0xa2, 0x59, 0x6a, 0x71, 0x65, 0xb2, 0xe3, 0xac,
	0x6f, 0x3a, 0xe8, 0x33, 0x07, 0x8a, 0xea, 0x59, 0xa0, 0xec, 0xb7, 0x28, 0xeb, 0x91, 0xcc, 0x71,
	0xe8, 0xe0, 0xb8, 0xfd, 0x75, 0xb4, 0x94, 0xa5, 0x22, 0x3b, 0xa6, 0xb1, 0xae, 0x56, 0x8e, 0x4f,
	0xa5, 0xb1, 0x87, 0x3d, 0xd9, 0x94, 0x70, 0x6f, 0x40, 0x18, 0x4f, 0x62, 0x2c, 0x3d, 0x91, 0x6b,
	0xd8, 0x48, 0x47, 0xa7, 0x31, 0x15, 0x9d, 0xdd, 0x7f, 0xe6, 0x8f, 0xdb, 0x7f, 0xce, 0xa3, 0x23,
	0xa8, 0xa8, 0x20, 0x7b, 0xed, 0xfb, 0x7b, 0xe8, 0xcb, 0x0f, 0x7a, 0x94, 0xcb, 0x91, 0xf7, 0x98,
	0x46, 0x91, 0xd7, 0xa5, 0x32, 0xe4, 0x41, 0x40, 0x38, 0xf7, 0x44, 0x62, 0x0e, 0x0a, 0xb1, 0xc0,
	0xcd, 0xb7, 0xd0, 0x72, 0x4f, 0x88, 0x01, 0xdf, 0x69, 0xb5, 0x62, 0x1a, 0xc7, 0xa4, 0x8f, 0xe3,
	0x8d, 0x84, 0x75, 0x1b, 0x97, 0x70, 0x44, 0x9e, 0xbc, 0x3b, 0x56, 0x05, 0x49, 0x7f, 0xbb, 0xb8,
	0xb9, 0xb1, 0xb9, 0xb1, 0xd5, 0x58, 0xc6, 0x03, 0xba, 0x21, 0x67, 0xed, 0xc9, 0xf5, 0x9c, 0x93,
	0xdb, 0x5e, 0xc2, 0x83, 0x41, 0x44, 0x03, 0x55, 0xa3, 0x5a, 0x0f, 0x79, 0x12, 0xef, 0xcc, 0x68,
	0xfc, 0x6b, 0x90, 0xbf, 0xb9, 0xb9, 0x89, 0xbe, 0x04, 0xb5, 0x5d, 0x1c, 0x7a, 0xe6, 0xfd, 0x6c,
	0xa0, 0x15, 0xb8, 0xdc, 0xc8, 0x60, 0x3d, 0x79, 0x86, 0xda, 0x7a, 0x4b, 0x5a, 0x1f, 0xc4, 0x38,
	0x15, 0xbd, 0x84, 0xd1, 0xef, 0x92, 0x70, 0x9e, 0xf5, 0x5b, 0xd2, 0xfa, 0x06, 0x6a, 0x42, 0xe5,
	0xbd, 0x84, 0x75, 0x68, 0x18, 0x92, 0x78, 0x9e, 0xe9, 0x2d, 0xc8, 0xdf, 0xda, 0xdc, 0x44, 0x1b,
	0xb0, 0xb2, 0x17, 0x0b, 0xd9, 0xff, 0x45, 0x9e, 0x6c, 0x75, 0x09, 0xf3, 0xbe, 0xc1, 0x58, 0xc2,
	0xe6, 0x2d, 0x7b, 0x5b, 0x2e, 0xdb, 0x46, 0x5f, 0x84, 0xaa, 0xf4, 0xfe, 0x2e, 0x16, 0xe4, 0x31,
	0x1e, 0xcd, 0x33, 0xbe, 0x21, 0x8d, 0x6f, 0xa0, 0x6b, 0x70, 0xd9, 0x74, 0xd1, 0xde, 0x41, 0x8c,
	0x87, 0x98, 0xea, 0xde, 0xf9, 0xfc, 0x45, 0x1f, 0x5f, 0x82, 0x8b, 0x50, 0xd9, 0xc5, 0x9c, 0x06,
	0xed, 0x54, 0xf4, 0x50, 0xae, 0xec, 0xfc, 0xf5, 0xf4, 0xf5, 0x0b, 0x9f, 0xff, 0xed, 0x75, 0xe7,
	0x63, 0xfd, 0x3f, 0x80, 0x8e, 0xab, 0x7e, 0x8f, 0xbf, 0xf1, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x1b, 0xdb, 0x45, 0x6f, 0x20, 0x18, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VinylClient is the client API for Vinyl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VinylClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	List(ctx context.Context, in *ListParams, opts ...grpc.CallOption) (Vinyl_ListClient, error)
	Get(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*ReleaseSource, error)
	Search(ctx context.Context, in *SearchParams, opts ...grpc.CallOption) (Vinyl_SearchClient, error)
	Store(ctx context.Context, in *StoreParams, opts ...grpc.CallOption) (*ReleaseSource, error)
}

type vinylClient struct {
	cc *grpc.ClientConn
}

func NewVinylClient(cc *grpc.ClientConn) VinylClient {
	return &vinylClient{cc}
}

func (c *vinylClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/vinyl.Vinyl/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vinylClient) List(ctx context.Context, in *ListParams, opts ...grpc.CallOption) (Vinyl_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Vinyl_serviceDesc.Streams[0], "/vinyl.Vinyl/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &vinylListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Vinyl_ListClient interface {
	Recv() (*ReleaseSource, error)
	grpc.ClientStream
}

type vinylListClient struct {
	grpc.ClientStream
}

func (x *vinylListClient) Recv() (*ReleaseSource, error) {
	m := new(ReleaseSource)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vinylClient) Get(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*ReleaseSource, error) {
	out := new(ReleaseSource)
	err := c.cc.Invoke(ctx, "/vinyl.Vinyl/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vinylClient) Search(ctx context.Context, in *SearchParams, opts ...grpc.CallOption) (Vinyl_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Vinyl_serviceDesc.Streams[1], "/vinyl.Vinyl/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &vinylSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Vinyl_SearchClient interface {
	Recv() (*ReleaseSource, error)
	grpc.ClientStream
}

type vinylSearchClient struct {
	grpc.ClientStream
}

func (x *vinylSearchClient) Recv() (*ReleaseSource, error) {
	m := new(ReleaseSource)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vinylClient) Store(ctx context.Context, in *StoreParams, opts ...grpc.CallOption) (*ReleaseSource, error) {
	out := new(ReleaseSource)
	err := c.cc.Invoke(ctx, "/vinyl.Vinyl/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VinylServer is the server API for Vinyl service.
type VinylServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	List(*ListParams, Vinyl_ListServer) error
	Get(context.Context, *GetParams) (*ReleaseSource, error)
	Search(*SearchParams, Vinyl_SearchServer) error
	Store(context.Context, *StoreParams) (*ReleaseSource, error)
}

func RegisterVinylServer(s *grpc.Server, srv VinylServer) {
	s.RegisterService(&_Vinyl_serviceDesc, srv)
}

func _Vinyl_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VinylServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vinyl.Vinyl/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VinylServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vinyl_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VinylServer).List(m, &vinylListServer{stream})
}

type Vinyl_ListServer interface {
	Send(*ReleaseSource) error
	grpc.ServerStream
}

type vinylListServer struct {
	grpc.ServerStream
}

func (x *vinylListServer) Send(m *ReleaseSource) error {
	return x.ServerStream.SendMsg(m)
}

func _Vinyl_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VinylServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vinyl.Vinyl/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VinylServer).Get(ctx, req.(*GetParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vinyl_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VinylServer).Search(m, &vinylSearchServer{stream})
}

type Vinyl_SearchServer interface {
	Send(*ReleaseSource) error
	grpc.ServerStream
}

type vinylSearchServer struct {
	grpc.ServerStream
}

func (x *vinylSearchServer) Send(m *ReleaseSource) error {
	return x.ServerStream.SendMsg(m)
}

func _Vinyl_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VinylServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vinyl.Vinyl/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VinylServer).Store(ctx, req.(*StoreParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vinyl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vinyl.Vinyl",
	HandlerType: (*VinylServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Vinyl_Health_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Vinyl_Get_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _Vinyl_Store_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Vinyl_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Search",
			Handler:       _Vinyl_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vinyl.proto",
}
