// Code generated by protoc-gen-go.
// source: artist.proto
// DO NOT EDIT!

/*
Package jams is a generated protocol buffer package.

It is generated from these files:
	artist.proto

It has these top-level messages:
	Area
	Type
	Artist
	ArtistCredit
	Event
	Label
	Place
	Recording
	Medium
	Duration
	Release
	ReleaseGroup
	Series
	URL
	Work
*/
package jams

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Area struct {
	Id          int32                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type        *Type                      `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	LastUpdated *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated" json:"last_updated,omitempty"`
	BeginDate   *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=begin_date,json=beginDate" json:"begin_date,omitempty"`
	EndDate     *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate" json:"end_date,omitempty"`
	Comment     string                     `protobuf:"bytes,7,opt,name=comment" json:"comment,omitempty"`
	IsoCodes    []string                   `protobuf:"bytes,8,rep,name=iso_codes,json=isoCodes" json:"iso_codes,omitempty"`
	Aliases     []string                   `protobuf:"bytes,9,rep,name=aliases" json:"aliases,omitempty"`
}

func (m *Area) Reset()                    { *m = Area{} }
func (m *Area) String() string            { return proto.CompactTextString(m) }
func (*Area) ProtoMessage()               {}
func (*Area) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Area) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Area) GetLastUpdated() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func (m *Area) GetBeginDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.BeginDate
	}
	return nil
}

func (m *Area) GetEndDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

type Type struct {
	Country      string `protobuf:"bytes,1,opt,name=country" json:"country,omitempty"`
	Subdivision  string `protobuf:"bytes,2,opt,name=subdivision" json:"subdivision,omitempty"`
	County       string `protobuf:"bytes,3,opt,name=county" json:"county,omitempty"`
	Municipality string `protobuf:"bytes,4,opt,name=municipality" json:"municipality,omitempty"`
	City         string `protobuf:"bytes,5,opt,name=city" json:"city,omitempty"`
	District     string `protobuf:"bytes,6,opt,name=district" json:"district,omitempty"`
	Island       string `protobuf:"bytes,7,opt,name=island" json:"island,omitempty"`
}

func (m *Type) Reset()                    { *m = Type{} }
func (m *Type) String() string            { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()               {}
func (*Type) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Artist struct {
}

func (m *Artist) Reset()                    { *m = Artist{} }
func (m *Artist) String() string            { return proto.CompactTextString(m) }
func (*Artist) ProtoMessage()               {}
func (*Artist) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ArtistCredit struct {
}

func (m *ArtistCredit) Reset()                    { *m = ArtistCredit{} }
func (m *ArtistCredit) String() string            { return proto.CompactTextString(m) }
func (*ArtistCredit) ProtoMessage()               {}
func (*ArtistCredit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Event struct {
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Label struct {
}

func (m *Label) Reset()                    { *m = Label{} }
func (m *Label) String() string            { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()               {}
func (*Label) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Place struct {
}

func (m *Place) Reset()                    { *m = Place{} }
func (m *Place) String() string            { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()               {}
func (*Place) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type Recording struct {
	Name   string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id     int32     `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Length *Duration `protobuf:"bytes,3,opt,name=length" json:"length,omitempty"`
}

func (m *Recording) Reset()                    { *m = Recording{} }
func (m *Recording) String() string            { return proto.CompactTextString(m) }
func (*Recording) ProtoMessage()               {}
func (*Recording) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Recording) GetLength() *Duration {
	if m != nil {
		return m.Length
	}
	return nil
}

type Medium struct {
}

func (m *Medium) Reset()                    { *m = Medium{} }
func (m *Medium) String() string            { return proto.CompactTextString(m) }
func (*Medium) ProtoMessage()               {}
func (*Medium) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Duration struct {
	Hours   int32 `protobuf:"varint,1,opt,name=hours" json:"hours,omitempty"`
	Minutes int32 `protobuf:"varint,2,opt,name=minutes" json:"minutes,omitempty"`
	Seconds int32 `protobuf:"varint,3,opt,name=seconds" json:"seconds,omitempty"`
}

func (m *Duration) Reset()                    { *m = Duration{} }
func (m *Duration) String() string            { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()               {}
func (*Duration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type Release struct {
}

func (m *Release) Reset()                    { *m = Release{} }
func (m *Release) String() string            { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()               {}
func (*Release) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type ReleaseGroup struct {
}

func (m *ReleaseGroup) Reset()                    { *m = ReleaseGroup{} }
func (m *ReleaseGroup) String() string            { return proto.CompactTextString(m) }
func (*ReleaseGroup) ProtoMessage()               {}
func (*ReleaseGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type Series struct {
}

func (m *Series) Reset()                    { *m = Series{} }
func (m *Series) String() string            { return proto.CompactTextString(m) }
func (*Series) ProtoMessage()               {}
func (*Series) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type URL struct {
}

func (m *URL) Reset()                    { *m = URL{} }
func (m *URL) String() string            { return proto.CompactTextString(m) }
func (*URL) ProtoMessage()               {}
func (*URL) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type Work struct {
}

func (m *Work) Reset()                    { *m = Work{} }
func (m *Work) String() string            { return proto.CompactTextString(m) }
func (*Work) ProtoMessage()               {}
func (*Work) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func init() {
	proto.RegisterType((*Area)(nil), "jams.Area")
	proto.RegisterType((*Type)(nil), "jams.Type")
	proto.RegisterType((*Artist)(nil), "jams.Artist")
	proto.RegisterType((*ArtistCredit)(nil), "jams.ArtistCredit")
	proto.RegisterType((*Event)(nil), "jams.Event")
	proto.RegisterType((*Label)(nil), "jams.Label")
	proto.RegisterType((*Place)(nil), "jams.Place")
	proto.RegisterType((*Recording)(nil), "jams.Recording")
	proto.RegisterType((*Medium)(nil), "jams.Medium")
	proto.RegisterType((*Duration)(nil), "jams.Duration")
	proto.RegisterType((*Release)(nil), "jams.Release")
	proto.RegisterType((*ReleaseGroup)(nil), "jams.ReleaseGroup")
	proto.RegisterType((*Series)(nil), "jams.Series")
	proto.RegisterType((*URL)(nil), "jams.URL")
	proto.RegisterType((*Work)(nil), "jams.Work")
}

func init() { proto.RegisterFile("artist.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x8b, 0xdb, 0x3c,
	0x10, 0xc6, 0x71, 0xd6, 0x76, 0xec, 0x49, 0xc8, 0x0b, 0xe2, 0xa5, 0x98, 0x14, 0x4a, 0xd0, 0xa1,
	0xe4, 0x94, 0x43, 0x4b, 0x0f, 0x3d, 0xf4, 0xb0, 0xec, 0x96, 0x5e, 0xb6, 0x50, 0xd4, 0x2c, 0x7b,
	0x0c, 0x8a, 0x35, 0xcd, 0x4e, 0x6b, 0x4b, 0x46, 0x92, 0x17, 0xf2, 0x05, 0x7b, 0xea, 0x87, 0x2a,
	0x92, 0xed, 0xb0, 0x3d, 0xed, 0x6d, 0x7e, 0xf3, 0x47, 0x23, 0x3d, 0x7a, 0x60, 0x29, 0xad, 0x27,
	0xe7, 0x77, 0x9d, 0x35, 0xde, 0xb0, 0xf4, 0xa7, 0x6c, 0xdd, 0xfa, 0x3f, 0x4f, 0x2d, 0x3a, 0x2f,
	0xdb, 0x6e, 0x48, 0xf3, 0x3f, 0x33, 0x48, 0xaf, 0x2d, 0x4a, 0xb6, 0x82, 0x19, 0xa9, 0x2a, 0xd9,
	0x24, 0xdb, 0x4c, 0xcc, 0x48, 0x31, 0x06, 0xa9, 0x96, 0x2d, 0x56, 0xb3, 0x4d, 0xb2, 0x2d, 0x45,
	0x8c, 0xd9, 0x1b, 0x48, 0xfd, 0xb9, 0xc3, 0xea, 0x6a, 0x93, 0x6c, 0x17, 0xef, 0x60, 0x17, 0x8e,
	0xdc, 0xed, 0xcf, 0x1d, 0x8a, 0x98, 0x67, 0x9f, 0x60, 0xd9, 0x48, 0xe7, 0x0f, 0x7d, 0xa7, 0xa4,
	0x47, 0x55, 0xa5, 0xb1, 0x6f, 0xbd, 0x3b, 0x19, 0x73, 0x6a, 0x70, 0xd8, 0x78, 0xec, 0x7f, 0xec,
	0xf6, 0xd3, 0x25, 0xc4, 0x22, 0xf4, 0xdf, 0x0f, 0xed, 0xec, 0x23, 0xc0, 0x11, 0x4f, 0xa4, 0x0f,
	0x01, 0xab, 0xec, 0xc5, 0xe1, 0x32, 0x76, 0xdf, 0x4a, 0x8f, 0xec, 0x03, 0x14, 0xa8, 0xd5, 0x30,
	0x98, 0xbf, 0x38, 0x38, 0x47, 0xad, 0xe2, 0x58, 0x05, 0xf3, 0xda, 0xb4, 0x2d, 0x6a, 0x5f, 0xcd,
	0xe3, 0x3b, 0x27, 0x64, 0xaf, 0xa1, 0x24, 0x67, 0x0e, 0xb5, 0x51, 0xe8, 0xaa, 0x62, 0x73, 0xb5,
	0x2d, 0x45, 0x41, 0xce, 0xdc, 0x04, 0x0e, 0x63, 0xb2, 0x21, 0xe9, 0xd0, 0x55, 0x65, 0x2c, 0x4d,
	0xc8, 0x7f, 0x27, 0x90, 0x06, 0x41, 0x86, 0x93, 0x7b, 0xed, 0xed, 0x39, 0x6a, 0x1a, 0x4f, 0x8e,
	0xc8, 0x36, 0xb0, 0x70, 0xfd, 0x51, 0xd1, 0x13, 0x39, 0x32, 0x7a, 0xd4, 0xf7, 0x79, 0x8a, 0xbd,
	0x82, 0x3c, 0x36, 0x9f, 0xa3, 0xd0, 0xa5, 0x18, 0x89, 0x71, 0x58, 0xb6, 0xbd, 0xa6, 0x9a, 0x3a,
	0xd9, 0x90, 0x3f, 0x47, 0x79, 0x4b, 0xf1, 0x4f, 0x2e, 0x7c, 0x5b, 0x1d, 0x6a, 0xd9, 0xf0, 0x6d,
	0x21, 0x66, 0x6b, 0x28, 0x14, 0x39, 0x6f, 0xa9, 0xf6, 0x51, 0x9c, 0x52, 0x5c, 0x38, 0xec, 0x22,
	0xd7, 0x48, 0xad, 0x46, 0x01, 0x46, 0xe2, 0x05, 0xe4, 0xd7, 0xd1, 0x3e, 0x7c, 0x05, 0xcb, 0x21,
	0xba, 0xb1, 0xa8, 0xc8, 0xf3, 0x39, 0x64, 0x9f, 0x9f, 0x50, 0xc7, 0xe0, 0x4e, 0x1e, 0xb1, 0x09,
	0xc1, 0xb7, 0x46, 0xd6, 0xc8, 0x1f, 0xa0, 0x14, 0x58, 0x1b, 0xab, 0x48, 0x9f, 0x2e, 0x06, 0x4a,
	0x9e, 0x19, 0x68, 0x30, 0xd9, 0xec, 0x62, 0xb2, 0xb7, 0x90, 0x37, 0xa8, 0x4f, 0xfe, 0x71, 0xb4,
	0xd4, 0x6a, 0xb0, 0xd4, 0x6d, 0x6f, 0xa5, 0x27, 0xa3, 0xc5, 0x58, 0x0d, 0xb7, 0xf9, 0x8a, 0x8a,
	0xfa, 0x96, 0xef, 0xa1, 0x98, 0xaa, 0xec, 0x7f, 0xc8, 0x1e, 0x4d, 0x6f, 0xdd, 0xe8, 0xda, 0x01,
	0x82, 0xf2, 0x2d, 0xe9, 0xde, 0xa3, 0x1b, 0x17, 0x4d, 0x18, 0x2a, 0x0e, 0x6b, 0xa3, 0x95, 0x8b,
	0xeb, 0x32, 0x31, 0x21, 0x2f, 0x61, 0x2e, 0xb0, 0x41, 0xe9, 0x30, 0x3c, 0x77, 0x0c, 0xbf, 0x58,
	0xd3, 0x77, 0x61, 0xf5, 0x77, 0xb4, 0x84, 0x8e, 0x67, 0x70, 0x75, 0x2f, 0xee, 0x78, 0x0e, 0xe9,
	0x83, 0xb1, 0xbf, 0x8e, 0x79, 0x34, 0xd6, 0xfb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xba, 0x66,
	0x7e, 0xed, 0x67, 0x03, 0x00, 0x00,
}
