// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/users/users.proto

package users

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthRequest struct {
	Uptime               string   `protobuf:"bytes,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Machine              string   `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ef18d8160d23c06, []int{0}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

func (m *HealthRequest) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *HealthRequest) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

type HealthResponse struct {
	Uptime               string   `protobuf:"bytes,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Machine              string   `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ef18d8160d23c06, []int{1}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *HealthResponse) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

type GetParams struct {
	Id                    string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                 string                  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AuthenticatedAccounts []*AuthenticatedAccount `protobuf:"bytes,3,rep,name=authenticated_accounts,json=authenticatedAccounts,proto3" json:"authenticated_accounts,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *GetParams) Reset()         { *m = GetParams{} }
func (m *GetParams) String() string { return proto.CompactTextString(m) }
func (*GetParams) ProtoMessage()    {}
func (*GetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ef18d8160d23c06, []int{2}
}

func (m *GetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParams.Unmarshal(m, b)
}
func (m *GetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParams.Marshal(b, m, deterministic)
}
func (m *GetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParams.Merge(m, src)
}
func (m *GetParams) XXX_Size() int {
	return xxx_messageInfo_GetParams.Size(m)
}
func (m *GetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetParams proto.InternalMessageInfo

func (m *GetParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetParams) GetAuthenticatedAccounts() []*AuthenticatedAccount {
	if m != nil {
		return m.AuthenticatedAccounts
	}
	return nil
}

type User struct {
	Id                    string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                 string                  `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password              string                  `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	AuthenticatedAccounts []*AuthenticatedAccount `protobuf:"bytes,5,rep,name=authenticated_accounts,json=authenticatedAccounts,proto3" json:"authenticated_accounts,omitempty"`
	Created               *timestamp.Timestamp    `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	Updated               *timestamp.Timestamp    `protobuf:"bytes,7,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted               *timestamp.Timestamp    `protobuf:"bytes,8,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ef18d8160d23c06, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetAuthenticatedAccounts() []*AuthenticatedAccount {
	if m != nil {
		return m.AuthenticatedAccounts
	}
	return nil
}

func (m *User) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *User) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *User) GetDeleted() *timestamp.Timestamp {
	if m != nil {
		return m.Deleted
	}
	return nil
}

type AuthenticatedAccount struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticatedAccount) Reset()         { *m = AuthenticatedAccount{} }
func (m *AuthenticatedAccount) String() string { return proto.CompactTextString(m) }
func (*AuthenticatedAccount) ProtoMessage()    {}
func (*AuthenticatedAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ef18d8160d23c06, []int{4}
}

func (m *AuthenticatedAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticatedAccount.Unmarshal(m, b)
}
func (m *AuthenticatedAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticatedAccount.Marshal(b, m, deterministic)
}
func (m *AuthenticatedAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticatedAccount.Merge(m, src)
}
func (m *AuthenticatedAccount) XXX_Size() int {
	return xxx_messageInfo_AuthenticatedAccount.Size(m)
}
func (m *AuthenticatedAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticatedAccount.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticatedAccount proto.InternalMessageInfo

func (m *AuthenticatedAccount) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthenticatedAccount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthRequest)(nil), "users.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "users.HealthResponse")
	proto.RegisterType((*GetParams)(nil), "users.GetParams")
	proto.RegisterType((*User)(nil), "users.User")
	proto.RegisterType((*AuthenticatedAccount)(nil), "users.AuthenticatedAccount")
}

func init() { proto.RegisterFile("pkg/users/users.proto", fileDescriptor_8ef18d8160d23c06) }

var fileDescriptor_8ef18d8160d23c06 = []byte{
	// 675 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xbe, 0x76, 0x7e, 0x9a, 0x4c, 0x6e, 0x7b, 0x7b, 0x47, 0x69, 0x89, 0x0c, 0x6a, 0x47, 0x46,
	0x42, 0x01, 0x51, 0xbb, 0x04, 0x16, 0xd0, 0x15, 0x2e, 0x8b, 0xc2, 0xae, 0x32, 0x65, 0xc3, 0xa6,
	0x9a, 0xda, 0xa7, 0xf6, 0x50, 0x7b, 0xc6, 0x78, 0xc6, 0x2d, 0x08, 0xb1, 0x41, 0x42, 0xec, 0xc3,
	0x0b, 0xb0, 0xe1, 0x1d, 0x78, 0x02, 0x1e, 0x00, 0x5e, 0x00, 0x01, 0x0f, 0x82, 0x3c, 0x76, 0x42,
	0x4a, 0x2a, 0x2a, 0x75, 0x93, 0x9c, 0xf3, 0x9d, 0xf3, 0x7d, 0xe7, 0xe4, 0xe4, 0xb3, 0xd1, 0x4a,
	0x76, 0x14, 0xb9, 0x85, 0x84, 0x5c, 0x56, 0x9f, 0x4e, 0x96, 0x0b, 0x25, 0x70, 0x4b, 0x27, 0x56,
	0x3f, 0x12, 0x91, 0xd0, 0x88, 0x5b, 0x46, 0x55, 0xd1, 0xba, 0x12, 0x09, 0x11, 0x25, 0xe0, 0xd2,
	0x8c, 0xb9, 0x94, 0x73, 0xa1, 0xa8, 0x62, 0x82, 0xd7, 0x54, 0x6b, 0xbd, 0xae, 0xea, 0xec, 0xa0,
	0x38, 0x74, 0x15, 0x4b, 0x41, 0x2a, 0x9a, 0x66, 0x75, 0xc3, 0x4d, 0xfd, 0x15, 0x6c, 0x44, 0xc0,
	0x37, 0xe4, 0x09, 0x8d, 0x22, 0xc8, 0x5d, 0x91, 0x69, 0x89, 0x79, 0x39, 0xdb, 0x43, 0x8b, 0x0f,
	0x81, 0x26, 0x2a, 0xf6, 0xe1, 0x79, 0x01, 0x52, 0xe1, 0x55, 0xd4, 0x2e, 0xb2, 0x52, 0x73, 0x60,
	0x10, 0x63, 0xd8, 0xf5, 0xeb, 0x0c, 0x0f, 0xd0, 0x42, 0x4a, 0x83, 0x98, 0x71, 0x18, 0x98, 0xba,
	0x30, 0x49, 0xed, 0x6d, 0xb4, 0x34, 0x91, 0x90, 0x99, 0xe0, 0x12, 0x2e, 0xa0, 0xf1, 0xd6, 0x40,
	0xdd, 0x1d, 0x50, 0xbb, 0x34, 0xa7, 0xa9, 0xc4, 0x4b, 0xc8, 0x64, 0x61, 0xcd, 0x35, 0x59, 0x88,
	0xfb, 0xa8, 0x05, 0x29, 0x65, 0x49, 0xcd, 0xaa, 0x12, 0xec, 0xa3, 0x55, 0x5a, 0xa8, 0x18, 0xb8,
	0x62, 0x01, 0x55, 0x10, 0xee, 0xd3, 0x20, 0x10, 0x05, 0x57, 0x72, 0xd0, 0x20, 0x8d, 0x61, 0x6f,
	0x74, 0xd9, 0xa9, 0x4e, 0xee, 0xcd, 0x36, 0x79, 0x55, 0x8f, 0xbf, 0x42, 0xcf, 0x40, 0xa5, 0xfd,
	0xc5, 0x44, 0xcd, 0x27, 0x12, 0xf2, 0xb9, 0x15, 0x30, 0x6a, 0x72, 0x9a, 0x4e, 0xf6, 0xd6, 0xf1,
	0xef, 0xb5, 0x1a, 0xb3, 0x6b, 0x59, 0xa8, 0x93, 0x51, 0x29, 0x4f, 0x44, 0x1e, 0x0e, 0x9a, 0xba,
	0x30, 0xcd, 0xff, 0xb2, 0x72, 0xeb, 0xa2, 0x2b, 0xe3, 0x3b, 0x68, 0x21, 0xc8, 0xa1, 0x84, 0x06,
	0x6d, 0x62, 0x0c, 0x7b, 0x23, 0xcb, 0xa9, 0x2c, 0xe2, 0x4c, 0x2c, 0xe2, 0xec, 0x4d, 0x2c, 0xe2,
	0x4f, 0x5a, 0x4b, 0x56, 0x91, 0x85, 0x9a, 0xb5, 0x70, 0x3e, 0xab, 0x6e, 0x2d, 0x59, 0x21, 0x24,
	0x50, 0xb2, 0x3a, 0xe7, 0xb3, 0xea, 0x56, 0x7b, 0x0b, 0xf5, 0xcf, 0xfa, 0x41, 0x67, 0xdd, 0x58,
	0xbd, 0xcc, 0xa6, 0x37, 0x2e, 0xe3, 0xd1, 0x67, 0x13, 0xb5, 0xca, 0x3f, 0x44, 0xe2, 0x77, 0x06,
	0x6a, 0x57, 0x3e, 0xc3, 0xfd, 0xfa, 0x4c, 0xa7, 0x9c, 0x6b, 0xad, 0xfc, 0x81, 0x56, 0x66, 0xb4,
	0x77, 0xc7, 0xde, 0x5d, 0xfc, 0x6f, 0x05, 0x92, 0x07, 0x31, 0x04, 0x47, 0xd6, 0xd0, 0x07, 0x55,
	0xe4, 0x5c, 0x12, 0x15, 0x03, 0x09, 0x8a, 0x3c, 0x07, 0xae, 0x88, 0x54, 0x54, 0x01, 0x11, 0x87,
	0x1a, 0x94, 0x90, 0x1f, 0xb3, 0x00, 0xde, 0x7c, 0xfd, 0xf9, 0xde, 0xfc, 0x0f, 0x2f, 0xd6, 0x8f,
	0x70, 0x5c, 0x8d, 0xdf, 0x47, 0x8d, 0x1d, 0x50, 0x78, 0xb9, 0x9e, 0x37, 0xf5, 0xad, 0xd5, 0xab,
	0x91, 0x72, 0x61, 0xfb, 0xde, 0xd8, 0xbb, 0x8a, 0x3b, 0x3b, 0xa0, 0x48, 0x99, 0x5a, 0x97, 0x7c,
	0x50, 0x39, 0x83, 0x63, 0x90, 0x84, 0x12, 0xc9, 0x78, 0x94, 0x00, 0x29, 0xbb, 0xf5, 0x88, 0x45,
	0xdc, 0xab, 0x47, 0xbc, 0x62, 0xe1, 0x6b, 0xec, 0xa3, 0xe6, 0x63, 0x7a, 0x0c, 0x78, 0x56, 0xef,
	0xb4, 0xf8, 0xe6, 0xd8, 0x5b, 0xc7, 0xdd, 0xb2, 0xa9, 0x52, 0xc7, 0x3a, 0x9c, 0x17, 0xee, 0xd8,
	0xed, 0x4a, 0x78, 0xfb, 0x93, 0x31, 0xf6, 0x3e, 0x1a, 0x18, 0x50, 0x57, 0x9f, 0x93, 0x78, 0xbb,
	0x8f, 0xf0, 0xb5, 0xbd, 0x98, 0xe9, 0x88, 0x9c, 0xb0, 0x24, 0x21, 0x11, 0x2b, 0x35, 0x82, 0x00,
	0xa4, 0x24, 0x4a, 0x68, 0x11, 0x12, 0x52, 0x45, 0xed, 0xeb, 0xb8, 0x1f, 0x2b, 0x95, 0xc9, 0x2d,
	0xd7, 0xe5, 0x8c, 0x73, 0x48, 0x29, 0x77, 0x44, 0x1e, 0x59, 0xff, 0xd3, 0x04, 0x5e, 0xdc, 0x9f,
	0x42, 0x81, 0x48, 0x47, 0xad, 0x4d, 0x67, 0xd3, 0xb9, 0x65, 0xf5, 0x69, 0xc6, 0x9c, 0xb2, 0x3a,
	0x5b, 0xbc, 0x61, 0x1a, 0xe6, 0x68, 0x99, 0x66, 0x59, 0x52, 0xfa, 0x80, 0x09, 0xee, 0x3e, 0x93,
	0x82, 0x6f, 0xcd, 0x21, 0xdf, 0xbe, 0xaf, 0xfd, 0xf3, 0xe1, 0xc7, 0x9a, 0xf1, 0xb4, 0x7a, 0x4d,
	0x1e, 0xb4, 0xb5, 0xb9, 0x6e, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xb7, 0xaf, 0x1a, 0x4d,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Get(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*User, error)
	Save(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/users.Users/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Get(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/users.Users/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Save(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/users.Users/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Get(context.Context, *GetParams) (*User, error)
	Save(context.Context, *User) (*User, error)
}

// UnimplementedUsersServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (*UnimplementedUsersServer) Health(ctx context.Context, req *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (*UnimplementedUsersServer) Get(ctx context.Context, req *GetParams) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUsersServer) Save(ctx context.Context, req *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.Users/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.Users/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Get(ctx, req.(*GetParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.Users/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Save(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Users_Health_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Users_Get_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _Users_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/users/users.proto",
}
