name: Node
on:
  push:
    branches-ignore:
      - master
jobs:
  build-ui:
    name: Build UI
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Node@v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/

    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Build
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
        mv $(pwd)/* $GOPATH/src/github.com/$GITHUB_REPOSITORY
        cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
        make generate

    # - name: Generate Docs
    #   run: |
    #     export GOPATH=$HOME/go
    #     export GOBIN=$(go env GOPATH)/bin
    #     export PATH=$PATH:$GOPATH
    #     export PATH=$PATH:$GOBIN
    #     cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
    #     make gen_docs

    - name: Build UI
      run: |
        cd $HOME/go/src/github.com/$GITHUB_REPOSITORY/ui
        npm i
        npm run-script build
        npm run-script lint

